### ISSUE TITLE
Does the code support RGBD mode?

### ISSUE THREAD

**Issue by dasda-asd** [AdaptSLAM/AdaptSLAM#3]
Can I run the RGBD dataset with this code? I see the monocular mode tested in the paper.

**Comment by i3tyc** [comment]
Hi @dasda-asd, it does not support RGBD mode.

**Comment by dasda-asd** [comment]
> Hi @dasda-asd, it does not support RGBD mode.

Thank you for your reply.
I noticed in the paper's description that the code was tested on the TUM dataset and EuRoC dataset in monocular mode. Can the code run on the KITTI dataset in monocular mode?

**Comment by i3tyc** [comment]
Hi @dasda-asd, to run the code on KITTI dataset, Examples/Monocular/mono_kitti.cc needs to be modified.  The rest of the code does not require any changes.

**Comment by dasda-asd** [comment]
> Thank you for your reply.

Thank you for your reply.
