### ISSUE TITLE
DATASET LINK WRONG

### ISSUE THREAD

**Issue by luxiangz** [AdaptSLAM/AdaptSLAM#4]
a. Download the [EuRoC V102 sequence](http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room2/V2_02_medium/V2_02_medium.zip).

**Comment by luxiangz** [comment]
http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip

**Comment by i3tyc** [comment]
Hi @luxiangz I just tested it and this link still works: http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip
Could you try to download it again?
